apiVersion: v2
appVersion: 0.11.0
deprecated: false
description: A network load-balancer implementation for Kubernetes using standard routing protocols
home: https://github.com/truecharts/apps/tree/master/charts/stable/metallb
icon: https://metallb.universe.tf/images/logo/metallb-white.png
keywords:
- metallb
- loadbalancer
dependencies:
- name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.11.0
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
name: metallb
sources:
  - https://github.com/metallb/metallb
  - https://metallb.universe.tf
type: application
version: 0.0.1
annotations:
  truecharts.org/catagories: |
    - core
  truecharts.org/SCALE-support: "false"
  truecharts.org/grade: U
